# Generated by Django 4.1.4 on 2023-01-05 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeID', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=50)),
                ('EmployeeEmail', models.CharField(max_length=50)),
                ('EmployeePhone', models.CharField(max_length=50)),
                ('DateOfBirth', models.DateField(default='2000-01-01')),
                ('Designation', models.CharField(max_length=50)),
                ('DateOfJoining', models.DateField(default='2000-01-01')),
                ('Salary', models.IntegerField(default=0)),
                ('Created_At', models.DateTimeField(auto_now_add=True, null=True)),
                ('Updated_At', models.DateTimeField(auto_now=True, null=True)),
                ('Created_By', models.CharField(default='Admin', max_length=50)),
                ('Is_Employee', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('ProjectID', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=50)),
                ('ProjectDescription', models.CharField(max_length=50)),
                ('ProjectManager', models.CharField(max_length=50)),
                ('ProjectStartDate', models.DateField(default='2000-01-01')),
                ('ProjectEndDate', models.DateField(default='2000-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('SkillID', models.AutoField(primary_key=True, serialize=False)),
                ('SkillName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SkillLevel', models.IntegerField(default=0)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('Skill', models.ManyToManyField(to='api.skills')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('Project', models.ManyToManyField(to='api.projects')),
            ],
        ),
    ]
