# Generated by Django 4.1.4 on 2023-01-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Created_At',
            new_name='CreatedAt',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Created_By',
            new_name='CreatedBy',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Is_Employee',
            new_name='IsEmployee',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Updated_At',
            new_name='UpdatedAt',
        ),
        migrations.AddField(
            model_name='employee',
            name='UpdatedBy',
            field=models.CharField(default='Admin', max_length=50),
        ),
        migrations.AddField(
            model_name='employeeprojects',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprojects',
            name='CreatedBy',
            field=models.CharField(default='Admin', max_length=50),
        ),
        migrations.AddField(
            model_name='employeeprojects',
            name='ProjectRole',
            field=models.CharField(default='Employee', max_length=50),
        ),
        migrations.AddField(
            model_name='employeeprojects',
            name='UpdatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprojects',
            name='UpdatedBy',
            field=models.CharField(default='Admin', max_length=50),
        ),
        migrations.AddField(
            model_name='employeeskills',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeskills',
            name='CreatedBy',
            field=models.CharField(default='Admin', max_length=50),
        ),
        migrations.AddField(
            model_name='employeeskills',
            name='UpdatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeskills',
            name='UpdatedBy',
            field=models.CharField(default='Admin', max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='CreatedBy',
            field=models.CharField(default='Admin', max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='UpdatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='UpdatedBy',
            field=models.CharField(default='Admin', max_length=50),
        ),
    ]
